[project]
name = "PO_O_Problema_Do_Poeta"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "gamspy>=1.18.1",
    "great-tables>=0.20.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "pyomo>=6.9.5",
]
